# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3da442df2250bd7abe98767a386683dc98188e3b0f82aced30400637acbd8473689d699acb64c30547c95cd385ccd4b4f7789a893ec966a2cf289798425e655

test:
  secret_key_base: 3496610b962e202ebb0c822e3a548403393c94439e905cd875f76f2e644f8b885c2b477469dadf7e9bb917e9da6856051deca995f1101084a0cc669d01a930a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
